language: minimal
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq curl
    - git clone https://github.com/oric-software/buildTestAndRelease.git
    - sh generateSdcard.sh
    - cd sdcard && tar -c * > ../sdcard.tar &&	cd ..
    - gzip sdcard.tar
    - mv sdcard.tar.gz sdcard.tgz
    - curl -F sdcard.tgz https://cdn.oric.org/publish.php?hash=${hash}&path=/home/oricoujr/www/ftp/orix/dists/2020.2/tgz/6502/sdcard.tgz
